[phases.setup]
nixPkgs = ["nodejs_20", "npm_10"]

[phases.install]
cmds = ["npm install --legacy-peer-deps", "npm install serve"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve -s build -l ${PORT:-3000}"
