#!/usr/bin/env python3
"""
generate_ratification_addenda.py — Tier-2 remediation packet generator.

Reads the 12 finalized initial-minutes records from production MongoDB and
renders, for each:
  1. A Ratification and Confirmation addendum (new signed record)
  2. Exhibit A: the corrected minutes, regenerated by the FIXED generator
     from the record's own template_data

NEVER modifies the database — read-only. Output: text files in the review
directory + a combined PDF for Jeff's review.

Usage:
  python3 scripts/generate_ratification_addenda.py --out <dir> [--db-url <mongo url>]

DB access defaults to MONGO_URL env var; falls back to localhost.
"""
import argparse
import asyncio
import os
import re
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

os.environ.setdefault("MONGO_URL", "mongodb://localhost:27017")
os.environ.setdefault("DB_NAME", "trustoffice")
os.environ.setdefault("JWT_SECRET", "packet-local")

STATE_NAMES = {
    "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas",
    "CA": "California", "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware",
    "FL": "Florida", "GA": "Georgia", "HI": "Hawaii", "ID": "Idaho",
    "IL": "Illinois", "IN": "Indiana", "IA": "Iowa", "KS": "Kansas",
    "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine", "MD": "Maryland",
    "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota", "MS": "Mississippi",
    "MO": "Missouri", "MT": "Montana", "NE": "Nebraska", "NV": "Nevada",
    "NH": "New Hampshire", "NJ": "New Jersey", "NM": "New Mexico", "NY": "New York",
    "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio", "OK": "Oklahoma",
    "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode Island", "SC": "South Carolina",
    "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas", "UT": "Utah",
    "VT": "Vermont", "VA": "Virginia", "WA": "Washington", "WV": "West Virginia",
    "WI": "Wisconsin", "WY": "Wyoming", "DC": "District of Columbia",
}

DIVIDER = "═" * 79


def fmt_date(value: str) -> str:
    """'2026-07-14' -> 'July 14, 2026'; passes through non-ISO strings."""
    if not value:
        return "[Date]"
    try:
        return datetime.strptime(str(value)[:10], "%Y-%m-%d").strftime("%B %d, %Y").replace(" 0", " ")
    except ValueError:
        return value


def fmt_time(value: str) -> str:
    """'18:00' -> '6:00 PM'; passes through already-formatted times."""
    if not value:
        return "[Time]"
    s = str(value)
    if "M" in s.upper():
        return s
    try:
        h, m = s.split(":")[:2]
        h = int(h)
        ampm = "AM" if h < 12 else "PM"
        h12 = h % 12 or 12
        return f"{h12}:{int(m):02d} {ampm}"
    except (ValueError, IndexError):
        return s


def state_name(code: str) -> str:
    return STATE_NAMES.get((code or "").upper(), code or "[State]")


def recital_flag_lines(t: dict) -> list:
    """Per-resolution recitals mapping adopted flags to plain-language statements."""
    lines = []
    if t.get("accept_trusteeship"):
        lines.append("acceptance of trusteeship by each Trustee")
    if t.get("acknowledge_fiduciary_duties"):
        lines.append("acknowledgment of fiduciary duties")
    if t.get("authorize_ein"):
        lines.append("authorization to obtain the Trust's EIN")
    if t.get("accept_initial_property"):
        lines.append("acceptance of initial trust property")
    if t.get("authorize_insurance"):
        lines.append("authorization to obtain insurance")
    if t.get("authorize_professional_services"):
        lines.append("authorization to engage professional services")
    if t.get("designate_record_keeper"):
        lines.append("designation of a record keeper")
    if t.get("adopt_governance_standards"):
        lines.append("adoption of governance standards")
    return lines


def build_addendum(doc: dict, trust: dict, corrected_minutes: str) -> str:
    mid = doc.get("minutes_id", "[ID]")
    t = doc.get("template_data") or {}
    trust_name = (trust or {}).get("name") or t.get("trust_name") or "[Trust Name]"
    state = (trust or {}).get("jurisdiction") or (trust or {}).get("state_code") or ""
    state_full = state_name(state) if state else ""
    trustees = (doc.get("template_data") or {}).get("trustees_present") or \
               (trust or {}).get("trustees") or ["[Trustee Name]"]
    mtg_date = fmt_date(t.get("meeting_date") or doc.get("created_at", "")[:10])
    form_date = fmt_date(t.get("trust_formation_date") or (trust or {}).get("start_date", ""))
    location = t.get("meeting_location") or ""
    governing = f"the laws of the State of {state_full}" if state_full else "applicable state law"
    res_count = len(re.findall(r"RESOLUTION \d+:", corrected_minutes))

    sig_block = "\n\n".join(
        f"_______________________________\n{name}, Trustee\n"
        "I confirm the actions listed in Exhibit A are correct and were made at "
        "the meeting.\nDate signed: _______________"
        for name in trustees)

    parts = [
        "ABOUT THIS DOCUMENT (please read first)",
        "This is a short form for you to sign. At your trustee meeting, certain "
        "decisions were made. The attached Exhibit A lists those decisions in "
        "full. By signing at the bottom you simply confirm those decisions are "
        "correct and official. No new decisions are being made, and nothing "
        "about your trust changes. (To ratify = to formally confirm something "
        "already done.) If you have questions, contact TrustOffice Support at "
        "support@trustoffice.app.",
        "",
        DIVIDER,
        "",
        "RATIFICATION AND CONFIRMATION OF INITIAL TRUSTEE MINUTES",
        trust_name,
        "",
        f"Addendum to Initial Trustee Meeting Minutes dated {mtg_date}",
        f"(Original record reference: {mid})",
        DIVIDER,
        "",
        "BACKGROUND",
        "",
        f"A. The Trust known as \"{trust_name}\" was established under a Trust "
        f"Instrument dated {form_date}, governed by {governing}.",
        "",
        f"B. The Trustees convened the initial organizational meeting of the Trust "
        f"on {mtg_date}" + (f", at {location}," if location else ",") +
        " and minutes of that meeting were prepared (the \"Original Minutes\").",
        "",
        "C. The Original Minutes, as prepared, did not set out, or did not fully "
        "set out, the resolutions adopted at the meeting.",
        "",
        "C-1. The Trustees confirm that Exhibit A accurately reflects the "
        "resolutions actually adopted at the organizational meeting and adopt it "
        "as the complete record of that meeting.",
        "",
        "D. The Trustees wish to ratify and confirm the actions taken at the "
        "organizational meeting and to adopt a complete and accurate record of "
        "those actions, as set out in Exhibit A attached to this Addendum.",
        "",
        "NOW, THEREFORE, the undersigned Trustees, constituting all of the "
        "Trustees of the Trust, do hereby resolve, ratify, and confirm:",
        "",
        "RATIFICATION",
        "",
        "1. Ratification of Organizational Actions. Each of the organizational "
        "actions described in Exhibit A is ratified, confirmed, and adopted as "
        f"the official action of the Trust, nunc pro tunc, effective as of "
        f"{mtg_date}.",
        "",
        "2. Ratification of Acts in Reliance. All acts taken by the Trustees in "
        "reliance on the Original Minutes or on the authority of the Trustees "
        "are ratified and confirmed. This Addendum does not ratify or confirm "
        "any acts taken by third parties, including banks or financial "
        "institutions.",
        "",
        "3. Complete Record. The restated minutes attached as Exhibit A, "
        "together with this Addendum, constitute the complete and accurate "
        "record of the initial organizational meeting. The Original Minutes "
        "remain part of the Trust's records.",
        "",
        "4. No Impairment. Nothing in this Addendum impairs, diminishes, or "
        "invalidates any action, authorization, or transaction previously taken "
        "or made under the Original Minutes or the authority of the Trustees.",
        "",
        "5. Governing Law; Forum. This Addendum and Exhibit A are governed by, "
        "and construed under, " + governing + ", which laws also govern the "
        "Trust Instrument. The Trustees submit to the exclusive jurisdiction of "
        "the courts of that State for any dispute arising from this Addendum.",
        "",
        "6. Severability. If any provision of this Addendum is held invalid or "
        "unenforceable, the remaining provisions remain in full force and "
        "effect.",
        "",
        "By signing below, the Trustees confirm this Addendum as of the date "
        "written.",
        "",
        sig_block,
        "",
        DIVIDER,
        "",
        "EXHIBIT A",
        "RESTATED MINUTES OF THE INITIAL ORGANIZATIONAL MEETING",
        "",
        "(Exhibit A is the complete, corrected version of the meeting minutes. "
        "For record-keeping it supplements and completes the Original Minutes, "
        "which stay in the Trust file; together with this Addendum it is the "
        "authoritative record of the meeting. It is not minutes of a new "
        "meeting, and no new business was transacted. Both documents describe "
        "the same meeting and the same decisions that were actually made.)",
        "",
        f"(The decisions shown below are all that were adopted at this meeting; "
        f"{res_count} resolutions in total. No additional resolutions were "
        f"passed.)",
        DIVIDER,
        "",
        corrected_minutes,
    ]
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True, help="Output directory")
    parser.add_argument("--db-url", default=os.environ.get("MONGO_URL", ""),
                        help="Mongo connection URL (or set MONGO_URL)")
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--preview", type=int, default=0,
                        help="Print first N chars of each addendum")
    args = parser.parse_args()

    from database import db  # connects at import using env
    from routers.minutes import generate_template_document

    os.makedirs(args.out, exist_ok=True)
    return asyncio.run(run_generate(args, db, generate_template_document))


async def run_generate(args, db, generate_template_document) -> int:
    query = {"template_type": "initial_trustee_meeting", "status": "final"}
    cursor = db.minutes_templates.find(query, {"_id": 0})
    if args.limit:
        cursor = cursor.limit(args.limit)

    written = 0
    docs = await cursor.to_list(length=args.limit or None)
    for doc in docs:
        mid = doc.get("minutes_id", "unknown")
        try:
            trust = None
            if doc.get("trust_id"):
                trust = await db.trusts.find_one(
                    {"trust_id": doc.get("trust_id")}, {"_id": 0})
            corrected = generate_template_document(
                trust or {}, doc.get("template_type"),
                doc.get("template_data") or {})
            if not corrected or "RESOLUTION 1" not in corrected:
                print(f"  FAIL {mid}: corrected minutes incomplete — NOT written")
                continue
            addendum = build_addendum(doc, trust or {}, corrected)
            path = os.path.join(args.out, f"{mid}_ratification_addendum.txt")
            with open(path, "w") as fh:
                fh.write(addendum)
            written += 1
            print(f"  WROTE {path} ({len(addendum)} chars)")
            if args.preview:
                print(addendum[: args.preview])
        except Exception as exc:  # noqa: BLE001
            print(f"  ERROR {mid}: {exc}")
    print(f"\nDone: {written} addenda written to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())