#!/usr/bin/env python3
"""
Generate frontend/src/pages/trustProtectorPowers.js from the canonical
backend/data/trust_protector_powers.json. Run after editing the JSON.

    python backend/scripts/generate_trust_protector_powers.py

The frontend and backend are separate Railway build contexts, so they cannot
share a single importable file. This script keeps them in sync by emitting the
frontend constant from the single source of truth. A drift check is provided by
check_trust_protector_drift.py.
"""
import json
import pathlib
import sys

BACKEND_DIR = pathlib.Path(__file__).resolve().parent.parent  # backend/
JSON_PATH = BACKEND_DIR / "data" / "trust_protector_powers.json"
FRONTEND_OUT = BACKEND_DIR.parent / "frontend" / "src" / "pages" / "trustProtectorPowers.js"


def render(powers):
    entries = []
    for p in powers:
        entries.append(
            f"  {{ value: {json.dumps(p['value'])}, label: {json.dumps(p['label'])}, "
            f"description: {json.dumps(p['description'])} }},"
        )
    return (
        "// AUTO-GENERATED by backend/scripts/generate_trust_protector_powers.py\n"
        "// Do not edit by hand. Source of truth: backend/data/trust_protector_powers.json\n"
        "// Regenerate with: python backend/scripts/generate_trust_protector_powers.py\n"
        "// (Run the drift check via backend/scripts/check_trust_protector_drift.py)\n"
        "export const TRUST_PROTECTOR_POWERS = [\n"
        + "\n".join(entries)
        + "\n];\n"
    )


def main():
    data = json.loads(JSON_PATH.read_text())
    powers = data["powers"]
    out = render(powers)
    if FRONTEND_OUT.exists() and FRONTEND_OUT.read_text() == out:
        print(f"unchanged: {FRONTEND_OUT}")
    else:
        FRONTEND_OUT.write_text(out)
        print(f"wrote: {FRONTEND_OUT}")
    print(f"powers: {len(powers)}")


if __name__ == "__main__":
    sys.exit(main())
