#!/usr/bin/env python3
"""Seed RICH demo examples for the Bennett & Lawson Family Office console.

2026-10-09 (Jeff): examples for showing people what advisors should expect to see.
Idempotent — dedupe on (trust_id, action, attribution). Adds:
  1. advisor-attributed org_activity rows (the rich action-doc schema the feed renders)
  2. human descriptions on the demo trusts' governance tasks (queue + calendar titles)
  3. one completed example (completed_via=org_queue) so 'completed by the firm' shows
Never creates trusts/users/minutes; only enriches what already exists.
"""
import sys
from datetime import datetime, timezone, timedelta
import pymongo

MONGO_URL = open("/Users/socializerender/.hermes/secrets/to-mongo-public.url").read().strip()
ORG = "org_162a37caadbc"
WEBB = "trust_dm2webb0000001"      # Marcus Webb
MARSH = "trust_dm2marsh0000002"    # Elena Marsh

NOW = datetime.now(timezone.utc)
def ts(days_ago, hour=10, minute=24):
    d = NOW - timedelta(days=days_ago)
    return d.replace(hour=hour, minute=minute, second=0, microsecond=0).isoformat()

def short_uuid():
    import uuid
    return "act_" + uuid.uuid4().hex[:12]

EVENTS = [
    # (days_ago, trust, action, member_name, attribution)
    (1, WEBB,  "minutes_finalized",       "Robert Johnson",  "Prepared by Robert Johnson, Bennett & Lawson Family Office — on behalf of Marcus Webb"),
    (2, MARSH, "schedule_a_item_added",   "Patricia Lawson", "Recorded by Patricia Lawson, Bennett & Lawson Family Office — on behalf of Elena Marsh"),
    (3, WEBB,  "distribution_notice_sent","Robert Johnson",  "Sent by Robert Johnson, Bennett & Lawson Family Office — on behalf of Marcus Webb"),
    (4, MARSH, "kit_generated",           "Greg Harman",     "Generated by Greg Harman, Bennett & Lawson Family Office — on behalf of Elena Marsh"),
    (5, MARSH, "minutes_autosaved",       "Patricia Lawson", "Drafted by Patricia Lawson, Bennett & Lawson Family Office — on behalf of Elena Marsh"),
    (6, WEBB,  "asset_updated",           "Greg Harman",     "Updated by Greg Harman, Bennett & Lawson Family Office — on behalf of Marcus Webb"),
    (8, MARSH, "meeting_recorded",        "Robert Johnson",  "Recorded by Robert Johnson, Bennett & Lawson Family Office — on behalf of Elena Marsh"),
    (11, WEBB, "grant_created",           "Marcus Webb",     "Marcus Webb granted Bennett & Lawson Family Office access"),
    (11, MARSH,"grant_created",           "Elena Marsh",     "Elena Marsh granted Bennett & Lawson Family Office access"),
]

TASK_TITLES = {
    "quarterly_review": "Quarterly account statements review",
    "transaction_review": "Review bank transactions for the period",
    "compensation_review": "Compensation plan review for the trustee",
    "insurance_review": "Insurance policies review",
    "annual_review": "Annual trust review",
    "beneficiary_meeting": "Beneficiary meeting",
    "tax_filing_review": "Tax filing review",
    "asset_revaluation": "Annual re-valuation of all Schedule A assets",
}

def main():
    c = pymongo.MongoClient(MONGO_URL, serverSelectionTimeoutMS=8000)
    db = c["trustoffice"]
    org = db.orgs.find_one({"org_id": ORG})
    assert org, "demo org missing"
    org_name = org.get("name") or "Bennett & Lawson Family Office"

    inserted = 0
    for days_ago, trust_id, action, member_name, attribution in EVENTS:
        exists = db.org_activity.find_one({
            "org_id": ORG, "trust_id": trust_id, "action": action, "attribution": attribution,
            "created_at": {"$gte": ts(days_ago - 0.5), "$lte": ts(days_ago + 0.5)},
        })
        if exists:
            continue
        db.org_activity.insert_one({
            "event_id": short_uuid(),
            "org_id": ORG,
            "trust_id": trust_id,
            "member_name": member_name,
            "org_name": org_name,
            "action": action,
            "attribution": attribution,
            "created_at": ts(days_ago),
        })
        inserted += 1
    print(f"activity rows inserted: {inserted}")

    # task descriptions so queue/calendar show human titles:
    updated = 0
    for tid in (WEBB, MARSH):
        for t in db.governance_tasks.find({"trust_id": tid, "$or": [{"description": {"$in": ["", None]}}, {"description": {"$exists": False}}]}):
            title = TASK_TITLES.get(t.get("task_type"))
            if not title:
                title = (t.get("task_type") or "task").replace("_", " ").title()
            db.governance_tasks.update_one({"_id": t["_id"]}, {"$set": {"description": title}})
            updated += 1
    print(f"governance tasks titled: {updated}")

    # one completed example (shows 'completed by the firm' trail in a client's workspace):
    done = db.governance_tasks.find_one({"trust_id": MARSH, "completed_via": "org_queue", "completed_at": {"$exists": True}})
    if not done:
        done = db.governance_tasks.find_one({"trust_id": MARSH, "completed_at": {"$exists": True}})
    if not done:
        src = db.governance_tasks.find_one({"trust_id": MARSH, "completed_at": None})
        if src:
            db.governance_tasks.update_one({"_id": src["_id"]}, {"$set": {
                "completed_at": ts(0, 9, 2),
                "completed_via": "org_queue",
                "completed_by_member_id": "member_dm2demo",  # demo owner member
            }})
            print("marked one Marsh task completed_via org_queue")
    print("seed done")

if __name__ == "__main__":
    main()
